name: "retail_sales"
version: '1.0'
config-version: 2
profile: demo_snowflake
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
models:
retail_sales:
  staging:
    +materialized: view
  intermediate:
    +materialized: incremental
    +incremental_strategy: merge
  marts:
    +materialized: table
