--creating storage integration with google cloud storage-----

CREATE STORAGE INTEGRATION ST_GCS_ORDERS_SI
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'GCS'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('gcs://raw_orders_csv_downloads');

---DESCRIBE STORAGE INTEGRATION TO SEE MORE DETAILS----

DESC STORAGE INTEGRATION ST_GCS_ORDERS_SI;

-----CREATING ONE MORE FILE FORMAT WITH MORE PARAMETERS SETTINGS---------
  
  CREATE  FILE FORMAT ST_GCS_CSV_FF
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 


---CREATING EXTERNAL STAGE WITH GCS LOCATION ALSO PROVIDE STORAGE INTEGRATION DETAILS AND FILE FORMAT TO USE---------

CREATE STAGE st_gcs_orders_ext_stage
  URL = 'gcs://raw_orders_csv_downloads'
  STORAGE_INTEGRATION = ST_GCS_ORDERS_SI
  FILE_FORMAT = ST_GCS_CSV_FF;

----DESCRIBE STAGE------
desc stage st_gcs_orders_ext_stage

---LIST ALL FILES FROM THIS STAGE-------
list @raw.st_gcs_orders_ext_stage







