name: "Allow merges to main only from develop"

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.event.pull_request.head.ref != 'develop'
        run: |
          echo "ERROR: Pull requests to main must come from develop branch."
          exit 1
